name: Sync to TU/e GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push main to TU/e GitLab
        run: |
          git push --force https://${{ github.actor }}:${{ secrets.GITLAB_PASSWORD }}@gitlab.tue.nl/k.penners/latency_in_llm_inference.git main:refs/heads/main
